# --- START OF FILE tag_definitions.py ---

# Este arquivo centraliza todas as tags personalizáveis da UI do sistema.
TAG_DEFINITIONS = {
    "Títulos Principais e Menus": {
        "main_window_title": "e-Votos - Sistema de Gestão Política",
        "municipios_list_label": "Municípios",
        "menu_config": "Configurações",
        "menu_reload_data": "Recarregar Dados",
        "menu_rebuild_db": "Reconstruir Banco de Dados...",
        "menu_import_contacts_obsolete": "Importar Contatos (obsoleto)...",
        "menu_create_backup": "Criar Backup Completo...",
        "menu_restore_backup": "Restaurar de um Backup...",
        "menu_edit_tags": "Editar Textos (tags UI)",
        "menu_search_candidate": "Buscar Candidato...",
        "menu_print": "Imprimir Relatório",
        "menu_tasks": "Gerenciar Tarefas",
        "menu_birthdays": "Aniversários",
        "menu_birthdays_candidates": "Candidatos",
        "menu_birthdays_cities": "Cidades",
        "menu_help": "Ajuda",
        "menu_exit": "Sair",
    },
    "Títulos de Seção (Relatório UI e HTML)": {
        "title_section_info": "INFORMAÇÕES MUNICIPAIS",
        "title_section_votos": "VOTAÇÃO SAULO",
        "title_section_executivo": "PODER EXECUTIVO",
        "title_section_legislativo": "PODER LEGISLATIVO",
        "title_city_suffix": " / SP",
    },
    "Rótulos: Informações Municipais (Tabelas)": {
        "label_prefeitura": "Prefeitura:",
        "label_cep": "CEP:",
        "label_cod_ibge": "Cód. IBGE:",
        "label_aniversario_cidade": "Aniversário:",
        "label_site": "Site:",
        "label_populacao": "População:",
        "label_dens_demografica": "Dens. Demográfica:",
        "label_email": "Email:",
        "label_tel": "Tel:",
        "label_gentilico": "Gentílico:",
        "label_area": "Área:",
        "label_area_suffix": "KM²",
        "label_idhm_geral": "IDHM Geral:",
        "label_idhm_longevidade": "Longevidade:",
        "label_idhm_renda": "Renda:",
        "label_idhm_educacao": "Educação:",
        "label_mulheres": "Mulheres (Eleitorado):",
        "label_homens": "Homens (Eleitorado):",
        "label_total": "Total (Eleitorado):",
    },
    "Rótulos: Cards de Candidatos (UI e HTML)": {
        "card_label_votos": "Votos:",
        "card_label_aniversario": "ANIVERSÁRIO:",
        "card_label_idade": "IDADE:",
        "card_label_idade_suffix": "anos",
    },
    "Popups Diversos": {
        "bday_city_title": "Próximos Aniversários de Cidades",
        "bday_city_none": "Nenhuma cidade aniversariante na próxima semana.",
        "bday_cand_title": "Próximos Aniversariantes (Eleição Ref.)",
        "bday_cand_none": "Nenhum aniversário (eleição referência) na próxima semana.",
        "edit_candidate_window_title_prefix": "Editar Contato",
        "global_search_window_title_prefix": "Busca Global de Candidatos",
        "dashboard_window_title_prefix": "Dashboard Municipal",
    },
    "Dicas de Interface (Tooltips da Barra de Status)": {
        "tooltip_pronto": "Pronto.",
        "tooltip_menu_painel": "Visualizar dashboard com estatísticas gerais do sistema.",
        "tooltip_menu_contatos": "Gerenciar a base de contatos de pessoas e organizações.",
        "tooltip_menu_atendimentos": "Registrar e acompanhar demandas e atendimentos.",
        "tooltip_menu_proposicoes": "Gerenciar projetos de lei, indicações e outras proposições.",
        "tooltip_menu_agenda": "Visualizar e agendar eventos e compromissos.",
        "tooltip_menu_cerimonial": "Gerar relatórios eleitorais detalhados por cidade.",
        "tooltip_menu_config": "Acessar configurações de administração, manutenção e importação.",
        "tooltip_menu_ajuda": "Ver informações de ajuda e histórico de atualizações.",
        "tooltip_menu_logoff": "Encerrar a sessão e retornar à tela de login.",
        # --- MUDANÇA PRINCIPAL AQUI ---
        "tooltip_card_candidato": "Clique para ver/editar o perfil de {nome} (ID: {id_pessoa})",
        "tooltip_contacts_nova_pessoa": "Adicionar um novo contato de pessoa ao sistema.",
        "tooltip_contacts_nova_org": "Adicionar uma nova organização ao sistema.",
        "tooltip_contacts_nova_lista": "Criar uma nova lista de contatos ou organizações.",
        "tooltip_contacts_lista_pessoas": "Filtrar contatos pela lista: '{list_name}'",
        "tooltip_contacts_treeview": "Lista de contatos. Clique para ver detalhes à direita ou clique duplo para editar.",
        "tooltip_settings_gerenciar_usuarios": "Adicionar, editar ou remover usuários do sistema.",
        "tooltip_settings_corrigir_duplicatas": "Fundir registros de pessoas duplicados com base em nome, CPF ou título de eleitor.",
        "tooltip_settings_criar_backup": "Salvar uma cópia de segurança dos dados e arquivos do sistema.",
        "tooltip_settings_restaurar_backup": "Restaurar o sistema a partir de um arquivo de backup. A aplicação será reiniciada.",
        "tooltip_settings_importar_prefeituras": "Importar/atualizar dados de municípios e eleitorado.",
        "tooltip_settings_importar_cadastrais": "Importar contatos e candidaturas a partir de um arquivo 'consulta_cand' do TSE.",
        "tooltip_settings_importar_votacao": "Importar os votos de uma eleição para atualizar os registros de candidaturas."
    }
}
# --- END OF FILE tag_definitions.py ---